import pandas as pd

df = pd.read_csv("network_logs,csv (path)", encoding="latin1")
print(df.columns)

# Keep only important columns
network_df = df[['Source', 'Destination', 'Protocol', 'Length', 'Info']]
network_df.head()

# Common Protocols 
print(network_df['Protocol'].value_counts().head(10))

# Top Source IP's 
print(network_df['Source'].value_counts().head(10))

network_alerts = []

# High network activity
source_counts = network_df['Source'].value_counts()

for ip, count in source_counts.items():
    if count > 20:
        network_alerts.append({
            "type": "HIGH_NETWORK_ACTIVITY",
            "ip": ip,
            "severity": "MEDIUM",
            "details": f"{count} packets detected"
        })

# Suspicious protocols
suspicious_protocols = ['FTP', 'TELNET', 'SMB']

for protocol in network_df['Protocol'].unique():
    if protocol in suspicious_protocols:
        network_alerts.append({
            "type": "SUSPICIOUS_PROTOCOL",
            "ip": "N/A",
            "severity": "HIGH",
            "details": f"Protocol detected: {protocol}"
        })

# Large packets
for index, row in network_df.iterrows():
    if row['Length'] > 1500:
        network_alerts.append({
            "type": "LARGE_PACKET",
            "ip": row['Source'],
            "severity": "MEDIUM",
            "details": f"{row['Length']} byte packet"
        })

# combine all alerts (wireshark and rule based)
all_alerts = alerts + network_alerts

for alert in all_alerts:
    print(alert)

# send email for high sevearity alerts 
for alert in all_alerts:
    if alert["ip"] != "N/A":
        country = get_country(alert["ip"])
    else:
        country = "Unknown"

    subject = f"🚨 {alert['severity']} Alert: {alert['type']}"

    body = f"""
Security Alert Detected

Type: {alert['type']}
Severity: {alert['severity']}
IP Address: {alert['ip']}
Location: {country}

Details: {alert['details']}

---
Generated by SIEM System
"""

    print(f"[{alert['severity']}] {alert['type']} from {alert['ip']} ({country}) → {alert['details']}")

    if alert["severity"] == "HIGH":
        send_email_alert(subject, body)



